version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  app:
    build: .
    container_name: sistema-ceub
    volumes:
      - .:/sistema-ceub:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
